<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="class2" nsURI="http://www.example.org/class2" nsPrefix="class2">
  <eClassifiers xsi:type="ecore:EClass" href="#//Faculty"/>
  <eClassifiers xsi:type="ecore:EClass" href="#//Course"/>
  <eClassifiers xsi:type="ecore:EClass" href="#//Professor"/>
  <eClassifiers xsi:type="ecore:EClass" href="#//Student"/>
  <eClassifiers xsi:type="ecore:EClass" href="#//Edition"/>
  <eClassifiers xsi:type="ecore:EClass" href="#//University"/>
  <eClassifiers xsi:type="ecore:EClass" href="#//CurricularUnit"/>
  <eClassifiers xsi:type="ecore:EClass" href="#//Grade"/>
</ecore:EPackage>
